/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package empleados;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class PanelPrincipal extends javax.swing.JFrame {
    private DefaultTableModel modeloTablaTraballador;
    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        modeloTablaTraballador = (DefaultTableModel)tblTraballadores.getModel();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PanelContenedorCentral = new javax.swing.JPanel();
        PanelIdTrabajador = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textApellido2 = new javax.swing.JTextField();
        textApellido1 = new javax.swing.JTextField();
        textDni = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        PanelContenedorDisponibles = new javax.swing.JPanel();
        btnEliminarEmpleado = new javax.swing.JButton();
        PanelTraballadoresDisponibles = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTraballadores = new javax.swing.JTable();
        PanelProvincia = new javax.swing.JPanel();
        cbProvincia = new javax.swing.JComboBox<>();
        txtProvincia = new javax.swing.JTextField();
        btnEliminarProvincia = new javax.swing.JButton();
        btnEngadirProvincia = new javax.swing.JButton();
        PanelProfesionTraballador = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        scrollProfesiones = new javax.swing.JScrollPane();
        ListProfesiones = new javax.swing.JList<>();
        PanelDetalleTraballador = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        PanelBotonesSur = new javax.swing.JPanel();
        btnEgandirTraballador = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 600));

        PanelContenedorCentral.setLayout(new java.awt.GridBagLayout());

        PanelIdTrabajador.setBorder(javax.swing.BorderFactory.createTitledBorder("Identificación do traballador"));

        jLabel1.setText("Nombre");

        jLabel2.setText("Dni");

        jLabel3.setText("Apelido 1");

        jLabel4.setText("Apelido 2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
            .addComponent(textApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(textApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIdTrabajadorLayout = new javax.swing.GroupLayout(PanelIdTrabajador);
        PanelIdTrabajador.setLayout(PanelIdTrabajadorLayout);
        PanelIdTrabajadorLayout.setHorizontalGroup(
            PanelIdTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIdTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIdTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textDni, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addComponent(textNombre)))
        );
        PanelIdTrabajadorLayout.setVerticalGroup(
            PanelIdTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIdTrabajadorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.3;
        PanelContenedorCentral.add(PanelIdTrabajador, gridBagConstraints);

        btnEliminarEmpleado.setText("Eliminar Traballador");
        btnEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadoActionPerformed(evt);
            }
        });

        PanelTraballadoresDisponibles.setBorder(javax.swing.BorderFactory.createTitledBorder("Traballadores Disponibles"));

        tblTraballadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome e apelidos", "Provincia", "Profesión"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTraballadores);

        javax.swing.GroupLayout PanelTraballadoresDisponiblesLayout = new javax.swing.GroupLayout(PanelTraballadoresDisponibles);
        PanelTraballadoresDisponibles.setLayout(PanelTraballadoresDisponiblesLayout);
        PanelTraballadoresDisponiblesLayout.setHorizontalGroup(
            PanelTraballadoresDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTraballadoresDisponiblesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelTraballadoresDisponiblesLayout.setVerticalGroup(
            PanelTraballadoresDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTraballadoresDisponiblesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelContenedorDisponiblesLayout = new javax.swing.GroupLayout(PanelContenedorDisponibles);
        PanelContenedorDisponibles.setLayout(PanelContenedorDisponiblesLayout);
        PanelContenedorDisponiblesLayout.setHorizontalGroup(
            PanelContenedorDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelTraballadoresDisponibles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnEliminarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelContenedorDisponiblesLayout.setVerticalGroup(
            PanelContenedorDisponiblesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContenedorDisponiblesLayout.createSequentialGroup()
                .addComponent(PanelTraballadoresDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarEmpleado)
                .addGap(14, 14, 14))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        PanelContenedorCentral.add(PanelContenedorDisponibles, gridBagConstraints);

        PanelProvincia.setBorder(javax.swing.BorderFactory.createTitledBorder("Provincia do traballador"));

        cbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coruña", "Lugo", "Orense", "Pontevedra" }));

        btnEliminarProvincia.setText("Eliminar Provincia");
        btnEliminarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProvinciaActionPerformed(evt);
            }
        });

        btnEngadirProvincia.setText("Engadir Provincia");
        btnEngadirProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngadirProvinciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProvinciaLayout = new javax.swing.GroupLayout(PanelProvincia);
        PanelProvincia.setLayout(PanelProvinciaLayout);
        PanelProvinciaLayout.setHorizontalGroup(
            PanelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProvinciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEngadirProvincia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PanelProvinciaLayout.setVerticalGroup(
            PanelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProvinciaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelProvinciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEngadirProvincia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.2;
        PanelContenedorCentral.add(PanelProvincia, gridBagConstraints);

        PanelProfesionTraballador.setBorder(javax.swing.BorderFactory.createTitledBorder("Profesión do traballador"));
        PanelProfesionTraballador.setMinimumSize(new java.awt.Dimension(0, 0));
        PanelProfesionTraballador.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 448;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 11, 0, 0);
        PanelProfesionTraballador.add(jTextField1, gridBagConstraints);

        jButton3.setText("Eliminar Profesion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 0, 5);
        PanelProfesionTraballador.add(jButton3, gridBagConstraints);

        jButton4.setText("Engadir Profesion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 5, 5);
        PanelProfesionTraballador.add(jButton4, gridBagConstraints);

        ListProfesiones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Electricista", "Carpintero", "Informático", "Abogado", "Antenista" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollProfesiones.setViewportView(ListProfesiones);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 496;
        gridBagConstraints.ipady = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 11, 0, 0);
        PanelProfesionTraballador.add(scrollProfesiones, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        PanelContenedorCentral.add(PanelProfesionTraballador, gridBagConstraints);

        PanelDetalleTraballador.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle do traballador"));

        jScrollPane3.setViewportView(jTextPane1);

        javax.swing.GroupLayout PanelDetalleTraballadorLayout = new javax.swing.GroupLayout(PanelDetalleTraballador);
        PanelDetalleTraballador.setLayout(PanelDetalleTraballadorLayout);
        PanelDetalleTraballadorLayout.setHorizontalGroup(
            PanelDetalleTraballadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleTraballadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDetalleTraballadorLayout.setVerticalGroup(
            PanelDetalleTraballadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleTraballadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        PanelContenedorCentral.add(PanelDetalleTraballador, gridBagConstraints);

        getContentPane().add(PanelContenedorCentral, java.awt.BorderLayout.CENTER);

        PanelBotonesSur.setPreferredSize(new java.awt.Dimension(735, 50));

        btnEgandirTraballador.setText("Engadir Trabajador");
        btnEgandirTraballador.setMargin(null);
        btnEgandirTraballador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgandirTraballadorActionPerformed(evt);
            }
        });

        jButton2.setText("Pechar Aplicacion");
        jButton2.setMargin(null);
        jButton2.setMaximumSize(new java.awt.Dimension(154, 24));
        jButton2.setMinimumSize(new java.awt.Dimension(154, 24));
        jButton2.setPreferredSize(new java.awt.Dimension(154, 24));

        javax.swing.GroupLayout PanelBotonesSurLayout = new javax.swing.GroupLayout(PanelBotonesSur);
        PanelBotonesSur.setLayout(PanelBotonesSurLayout);
        PanelBotonesSurLayout.setHorizontalGroup(
            PanelBotonesSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesSurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEgandirTraballador, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelBotonesSurLayout.setVerticalGroup(
            PanelBotonesSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesSurLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(PanelBotonesSurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEgandirTraballador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(PanelBotonesSur, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEmpleadoActionPerformed

    private void textDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDniActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEngadirProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngadirProvinciaActionPerformed
        engadirProvincia();
    }//GEN-LAST:event_btnEngadirProvinciaActionPerformed

    private void btnEliminarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProvinciaActionPerformed
        eliminarProvincia(); 
    }//GEN-LAST:event_btnEliminarProvinciaActionPerformed

    private void btnEgandirTraballadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgandirTraballadorActionPerformed
        Empleado e = new Empleado(
                textDni.getText(),
                textNombre.getText(),
                textApellido1.getText(), 
                textApellido2.getText(),
                cbProvincia.getSelectedItem().toString(),
                ListProfesiones.getSelectedValue());
      

        engadirEmpleado(e);
    }//GEN-LAST:event_btnEgandirTraballadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelPrincipal().setVisible(true);
            }
        });
    }
    
    private void engadirEmpleado(Empleado e){
        //Engadir o moble á táboa    // Obtener el modelo de la tabla
        // Crear una nueva fila con los datos del empleado
        Object[] fila = {e, e.getProvincia(), e.getProfesion()};
       // Añadir la nueva fila al modelo
       modeloTablaTraballador.addRow(fila);

    }

    private void engadirProvincia(){
        String provincia = String.valueOf(txtProvincia.getText());
        
        if(!provincia.isEmpty()){
            cbProvincia.addItem(txtProvincia.getText());
        }
        else{
            System.out.println("Escriba una provincia");
        }
    }
   
    private void eliminarProvincia(){
        cbProvincia.removeItem(cbProvincia.getSelectedItem());
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListProfesiones;
    private javax.swing.JPanel PanelBotonesSur;
    private javax.swing.JPanel PanelContenedorCentral;
    private javax.swing.JPanel PanelContenedorDisponibles;
    private javax.swing.JPanel PanelDetalleTraballador;
    private javax.swing.JPanel PanelIdTrabajador;
    private javax.swing.JPanel PanelProfesionTraballador;
    private javax.swing.JPanel PanelProvincia;
    private javax.swing.JPanel PanelTraballadoresDisponibles;
    private javax.swing.JButton btnEgandirTraballador;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnEliminarProvincia;
    private javax.swing.JButton btnEngadirProvincia;
    private javax.swing.JComboBox<String> cbProvincia;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JScrollPane scrollProfesiones;
    private javax.swing.JTable tblTraballadores;
    private javax.swing.JTextField textApellido1;
    private javax.swing.JTextField textApellido2;
    private javax.swing.JTextField textDni;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
}


