/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menusexanelas;

/**
 *
 * @author borjaoteroferreira
 */
public class MenuContextual extends javax.swing.JFrame {

    /**
     * Creates new form PanelConLabel
     */
    public MenuContextual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        opOpcions = new javax.swing.JMenu();
        opEditar = new javax.swing.JMenu();
        opEditarTexto = new javax.swing.JMenuItem();
        opColores = new javax.swing.JMenu();
        opCambiarColor = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        opIdiomas = new javax.swing.JMenu();
        opCastellano = new javax.swing.JMenuItem();
        opGalego = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();

        opOpcions.setText("Opcions");

        opEditar.setText("Editar");

        opEditarTexto.setText("Editar Texto");
        opEditar.add(opEditarTexto);

        opColores.setText("Color");

        opCambiarColor.setText("Cambiar Color");
        opColores.add(opCambiarColor);

        opEditar.add(opColores);

        opOpcions.add(opEditar);

        jMenuItem5.setText("Desactivar Notificaciones");
        opOpcions.add(jMenuItem5);

        jPopupMenu1.add(opOpcions);

        opIdiomas.setText("Idiomas");

        opCastellano.setText("Castellano");
        opIdiomas.add(opCastellano);

        opGalego.setText("Galego");
        opIdiomas.add(opGalego);

        jPopupMenu1.add(opIdiomas);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Prema co botón dereito sobre esta etiqueta para despregar o menú contextual");
        jLabel1.setComponentPopupMenu(jPopupMenu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuContextual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuContextual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuContextual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuContextual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuContextual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem opCambiarColor;
    private javax.swing.JMenuItem opCastellano;
    private javax.swing.JMenu opColores;
    private javax.swing.JMenu opEditar;
    private javax.swing.JMenuItem opEditarTexto;
    private javax.swing.JMenuItem opGalego;
    private javax.swing.JMenu opIdiomas;
    private javax.swing.JMenu opOpcions;
    // End of variables declaration//GEN-END:variables
}
